# Autogenerated wrapper script for hyper_jll for aarch64-apple-darwin
export libhyper

JLLWrappers.@generate_wrapper_header("hyper")
JLLWrappers.@declare_library_product(libhyper, "@rpath/libhyper.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libhyper,
        "lib/libhyper.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
