# Autogenerated wrapper script for hyper_jll for x86_64-unknown-freebsd
export libhyper

JLLWrappers.@generate_wrapper_header("hyper")
JLLWrappers.@declare_library_product(libhyper, "libhyper.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libhyper,
        "lib/libhyper.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
