# Autogenerated wrapper script for hyper_jll for x86_64-w64-mingw32
export libhyper

JLLWrappers.@generate_wrapper_header("hyper")
JLLWrappers.@declare_library_product(libhyper, "libhyper.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libhyper,
        "bin\\libhyper.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
